name: m_club
description: M-Club mobile app
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_html: ^3.0.0-beta.2
  share_plus: ^10.0.0

  # Навигация
  go_router: ^14.1.0

  # Сеть / данные / хранилище
  http: ^1.2.0
  xml: ^6.3.0
  provider: ^6.1.0
  shared_preferences: ^2.2.3

  # Локализация
  intl: ^0.20.2

  # Гео и карты
  geolocator: ^10.1.0
  google_maps_flutter: ^2.6.0
  permission_handler: ^11.3.0
  device_info_plus: ^10.1.0

  # Мультимедиа и ссылки
  url_launcher: ^6.3.0

  # UI
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  flutter_svg: ^2.0.10+1
  palette_generator: ^0.3.3+7
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
